import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning className={inter.className}>
        <body className="min-h-full flex flex-col bg-background text-foreground">
          <Header />
          <main className="min-h-screen">
            {children}
          </main>

          <Toaster richColors />
        </body>
      </html>
    </ClerkProvider>
  );
}